name: lifetravel.de
favicon: null
layout_spectrum: 0.9886029290501028
typography_spectrum: 0.9269793927669525
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8246887491550297
  lightness: 0.5723942175973207
  saturation: 0.47030100249685347
  rhythmicContrast: 0.7895612500142306
purpose: []
